In [1]:
import pandas as pd
import numpy as np

In [52]:
ss = pd.read_csv("startup_cleaned_r.csv")
# ss.info()
ss['date'] = ss['date'].replace('05/072018', '05-07-2018')
ss['date'] = pd.to_datetime(ss['date'])
ss['year'] = ss['date'].dt.year
ss['month'] = ss['date'].dt.month
ss['day'] = ss['date'].dt.day
ss.info()
ss.to_csv("Startup_data1.csv",index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2822 entries, 0 to 2821
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         2822 non-null   datetime64[ns]
 1   startup      2822 non-null   object
 2   vertical     2822 non-null   object
 3   subvertical  2078 non-null   object
 4   city         2822 non-null   object
 5   investors    2822 non-null   object
 6   round        2822 non-null   object
 7   amount       2822 non-null   float64
 8   year         2822 non-null   int32
 9   month        2822 non-null   int32
 10  day          2822 non-null   int32
dtypes: datetime64[ns](1), float64(1), int32(3), object(6)
memory usage: 209.6+ KB

In [53]:
aa=ss[['date', 'city', 'startup', 'amount']]
aa
ss['month'].drop_duplicates()

0       9
1       1
3       2
6      10
7      12
8       6
9       3
14     11
30      4
33      5
47      8
160     7
Name: month, dtype: int32

In [ ]:
# startup analysis part
# ss.groupby('startup')['investors'].count().dropna()
# ss['startup']=ss['startup'].str.capitalize()
ss.groupby('startup')['investors'].count()
# ss['startup']

# ss.groupby('year')['amount'].sum().split(".")

AttributeError: 'Series' object has no attribute 'split'

In [75]:
ss.groupby('startup')['amount'].sum().sort_values(ascending=False).head(10)

startup
Flipkart            33492.5250
Rapido Bike Taxi    32175.0000
Paytm               25978.8375
Ola                  8122.1250
Udaan                7177.5000
Flipkart.com         5775.0000
Snapdeal             5775.0000
Ola Cabs             5525.0250
BigBasket            4182.7500
GOQii                3712.5000
Name: amount, dtype: float64

In [ ]:
startup_name = 'Flipkart'

ss['investors'] = ss['investors'].astype(str).str.split(',')
ss['investors']
investors = (
    ss['investors']
    .dropna()
    .astype(str)
    .str.split(',')
)
investors

In [ ]:
ss.groupby('startup')['investors']
dd=ss.groupby('startup')['investors'].count()
dd
result = ss.groupby('year')['amount'].sum()

split_result = result.astype(str).str.split('.', expand=True)

print(split_result)

Series([], Name: investors, dtype: int64)

vertical
360-degree view creating platform                            0.000
3D Printer Manufacturer                                     24.750
AI                                                           0.000
API Workflow platform                                        8.250
Accounting                                                  41.250
                                                             ...
solar products and services marketplace                      0.000
us ticketing and fleet management platform                   0.000
usiness expense management                                   4.125
virtual reality, 3d simulation and stereoscopic products     6.600
visual search and discovery platform                         8.250
Name: amount, Length: 798, dtype: float64

In [47]:

# ss['startup']=ss['startup'].str.replace('\\xc2\\xa0nudgespot ','unknown')
# ss['startup']=ss['startup'].str.replace("byju\\'s",'byju')
# ss['startup']=ss['startup'].str.replace("121policy ",'policy')
# ss['startup']=ss['startup'].str.replace("19th mile ",'mile')
ss.groupby('startup')['investors'].count()
# ss['startup']=ss['startup'].value_counts()
ss.groupby('startup')['investors'].count()

Series([], Name: investors, dtype: int64)

In [6]:
ss[ss['year'] == 2019][['date', 'city', 'startup', 'amount']]
ss.head()

,date,startup,vertical,subvertical,city,investors,round,amount,year,month,day
0,2020-09-01,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,1650.000000,2020,9,1
1,2020-01-13,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,66.399250,2020,1,13
2,2020-09-01,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,151.460595,2020,9,1
3,2020-02-01,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,24.750000,2020,2,1
4,2020-02-01,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,14.850000,2020,2,1

In [3]:
ss['year'].dropna()

0       2020
1       2020
2       2020
3       2020
4       2020
        ...
2817    2015
2818    2015
2819    2015
2820    2015
2821    2015
Name: year, Length: 2822, dtype: int32

In [27]:
# ss.info()
ss['date'] = ss['date'].replace('05/072018', '05/07/2018')
ss['date'] = pd.to_datetime(ss['date'], dayfirst=True, errors='coerce')
# ss = ss.dropna(subset=['date'])
# ss.info()
# ss = ss.dropna(subset=['date'])

# Year only


ss['year'] = ss['date'].dt.year


ss['month'] = ss['date'].dt.month
ss['day'] = ss['date'].dt.day
ss.to_csv("Startup_data.csv",index=False)
ss.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1205 entries, 0 to 2777
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         1205 non-null   datetime64[ns]
 1   startup      1205 non-null   object
 2   vertical     1205 non-null   object
 3   subvertical  891 non-null    object
 4   city         1205 non-null   object
 5   investors    1205 non-null   object
 6   round        1205 non-null   object
 7   amount       1205 non-null   float64
 8   year         1205 non-null   int32
 9   month        1205 non-null   int32
 10  day          1205 non-null   int32
dtypes: datetime64[ns](1), float64(1), int32(3), object(6)
memory usage: 98.8+ KB

In [ ]:
ss.groupby()
ss['s']

In [ ]:
ss['startup']=ss['startup'].str.replace('Byju\\\\xe2\\\\x80\\\\x99s','unknown')

In [2]:
df1 = pd.read_csv("/content/ipl-matches_data.csv")
df1.head()
df2=pd.read_csv('/content/ipl20081.csv')
d=df1[df1['Season'] == '2016'][['City','Season']]
print(d.drop_duplicates().count().head())

FileNotFoundError: [Errno 2] No such file or directory: '/content/ipl-matches_data.csv'

In [3]:
df=pd.read_csv("startup_funding (1).csv")

In [4]:
df.head()
df['Amount in USD']=df['Amount in USD'].fillna('0')
df['Amount in USD'].astype()
df['Amount in USD'].str.replace()

TypeError: NDFrame.astype() missing 1 required positional argument: 'dtype'

In [5]:
df1=pd.read_csv("clin_startup.csv")
# df1.info()
# df1.info()
df1.dropna(subset=['startup','vertical','city','investors','round','amount'],inplace=True)

In [6]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3044 non-null   object
 1   startup      3044 non-null   object
 2   vertical     3044 non-null   object
 3   subVertical  3044 non-null   object
 4   city         3044 non-null   object
 5   investors    3044 non-null   object
 6   round        3044 non-null   object
 7   amount       3044 non-null   object
dtypes: object(8)
memory usage: 190.4+ KB

In [7]:
df1['startup']=df1['startup'].str.replace('https://www.wealthbucket.in/','unknown')
df1['startup']=df1['startup'].str.replace('Byju\\\\xe2\\\\x80\\\\x99s','unknown')

df1['startup']=df1['startup'].str.replace('Tilite Technologies Pvt. Ltd','Tilite Technologies Pvt')
df1['startup']=df1['startup'].str.replace('.',' ')
df1['startup']=df1['startup'].str.replace('Creator\\\\xe2\\\\x80\\\\x99s Gurukul','unknown')
df1['startup']=df1['startup'].str.replace('What\\\\xe2\\\\x80\\\\x99s Up Life','unknown')
df1['startup']=df1['startup'].str.replace('\\\\','unknown')
df1['startup']=df1['startup'].str.replace('75F','unknown')
df1['startup']=df1['startup'].str.replace('\\','unknown')
df1['startup']=df1['startup'].str.replace('SERV\\xe2\\x80\\x99D','unknown')

In [8]:
sorted(tuple(list(df1['startup'].drop_duplicates().unique())))

['"BYJUunknown\'S"',
 '#Fame',
 '121Policy',
 '19th mile',
 '1Crowd',
 '1mg',
 '1mg (Healthkartplus)',
 '20Dresses',
 '33Coupons',
 '360Ride',
 '3Dexter',
 '3HCare',
 '3rdFlix',
 '48East',
 '4tigo',
 '5th Vital',
 '6Degree',
 '91SpringBoard',
 '99Games',
 '99PerHour',
 '9Stacks',
 'A&R Bon Vivants',
 'ABI Health',
 'AEON Learning',
 'AHA Taxis',
 'AYE Finance',
 'AadharAPI com',
 'Aadyah',
 'Aahaa',
 'Aahaa Stores',
 'Aarav UAV',
 'Aasaanjobs',
 'Aashiyaan',
 'Aavishkaar-Intellecap Group',
 'AbeRuk',
 'Abhibus',
 'Absentia',
 'Absentia VR',
 'Ace Turtle',
 'Ace2three',
 'Acko',
 'ActOnMagic',
 'Actionable Analytics',
 'Active AI',
 'Active ai',
 'Actofit',
 'Ad2pro',
 'AdPushUp',
 'AdStringO',
 'AdUrCup',
 'AdWyze',
 'Address Health',
 'AdmitKard',
 'Advanced Structures India',
 'Advantage Club',
 'Advenio',
 'Adytude',
 'Aequm',
 'AerMed',
 'Affimity',
 'Affordplan',
 'Agara Labs',
 'AgentDesks',
 'Agricxlab',
 'Agrostar',
 'Agrowave',
 'AirCTO',
 'AirMed Labs',
 'AirZaar',
 'Airpay',
 'Airwood',
 'Aisle',
 'Aisle co',
 'Akosha',
 'AlefunknownnMobitech',
 'AllIzHealth',
 'Allygrow Technologies',
 'AlmaConnect',
 'AlmaMapper',
 'Alpha Capital',
 'Alteria Capital',
 'Alternacare',
 'Altizone',
 'Amagi Media Labs',
 'Ambee',
 'American Vision',
 'Amigobulls',
 'Ampere',
 'Ampere Vehicles',
 'Anakage',
 'Anandakanda',
 'Anchanto',
 'Annapurna Finance',
 'Antuit',
 'AppBrowzer',
 'AppDaily',
 'AppLop',
 'AppVirality',
 'Appario Retail Pvt Ltd ',
 'Appbase',
 'Appedo',
 'Appie',
 'AppilyEver',
 'Appknox',
 'Applicate',
 'Applied Solar Technologies',
 'Applop',
 'AppsDaily',
 'Appsdaily',
 'Appvigil',
 'Arcatron',
 'Arcatron Mobility',
 'Ark Robot',
 'Arkin Net',
 'Arohan Financial Services',
 'Arth DesignBuild',
 'Artoo',
 'Arya ai',
 'Aryaka',
 'Asia Institute Of Medical Science',
 'AskMyGift',
 'Asocon',
 'Ather Energy',
 'Athletto',
 'Atlan',
 'Atomberg',
 'Atomberg Technology',
 'Attune Technologies',
 'Augrav',
 'AutoGrid',
 'AutoSense',
 'Autobix',
 'Automation Anywhere',
 'Autorox co',
 'Avagmah',
 'Avail Finance',
 'AvailFinance',
 'Avanti Learning',
 'Avenue Growth',
 'Avishkaar Box',
 'Awaaz De',
 'Awesummly',
 'Awfis',
 'Awign',
 'Axio',
 'Axtria',
 'Aye Finance',
 'AyeFinance',
 'Azah',
 'Azuro',
 'B9 Beverages',
 'BHIVE',
 'BHIVE Workspace',
 'BRIDGEi2I',
 'BYG',
 'BYJUunknownxe2unknownx80unknownx99s',
 'BYJU’S',
 'Babajobs',
 'Baby Berry',
 'BabyChakra',
 'Babychakra',
 'Babygogo',
 'BabyonBoard',
 'Badiyajobs',
 'BaggOut',
 'Balance App',
 'Banihal',
 'Bank Bazaar',
 'BankBazaar',
 'BankerBay',
 'Bats on delivery',
 'Baxi',
 'Be U Salons',
 'BeaconsTalk',
 'Beardo',
 'BeatRoute',
 'BedBathMore',
 'Belita',
 'Belong',
 'Benepik',
 'Bestdealfinance',
 'BetaOut',
 'Betaout',
 'Better Mortgage',
 'BetterButter in',
 'BetterPlace',
 'Betterplace',
 'Bevy',
 'Bewakoof',
 'Beyond Evolution',
 'Bharat Bazaar',
 'BharatPe',
 'BhiveWorkspace',
 'BiBox',
 'Bidgely',
 'Big Basket',
 'Big Fish Ventures',
 'BigBasket',
 'BigStylist',
 'BigStylist com',
 'Bikxie',
 'BillDesk',
 'Billion Loans',
 'Bira91',
 'Biryani Blues',
 'Biryani By Kilo',
 'BitGiving',
 'Bite Club',
 'Biteclub',
 'Bitla Software',
 'Biz2Credit',
 'Bizom',
 'Bizongo',
 'Black Soil',
 'Black White Orange',
 'Black White Orange Brands',
 'BlackBuck',
 'Blackbuck',
 'Blinge',
 'BlogBeats',
 'Blood n Care',
 'Blowhorn',
 'Blubox',
 'Blue Box Media',
 'Blue Tokai Coffee',
 'BlueStone',
 'Bluebirch',
 'Bluegape',
 'Bluegape com',
 'Board Infinity',
 'Bobble',
 'BoiBanit',
 'BolRealty',
 'Bollant Industries',
 'Bolo App',
 'Bombay Shaving Company',
 'Bombay Shirt Company',
 'Bona Vita',
 'Bonhomia',
 'Bonphulapl',
 'Book My Diamond',
 'Book My Show',
 'Book Servicing',
 'BookEventz',
 'BookMeIn',
 'BookMyBai',
 'BookMyShow',
 'Bottr me',
 'Bounty App',
 'Box My Space',
 'Box8',
 'Boxmyspace',
 'Boxx ai',
 'Brick2Wall',
 'Brigge',
 'Briston Technomach',
 'Bro4U',
 'BroEx',
 'Broomberg',
 'Browntape',
 'BrowserStack',
 'Bucker',
 'Buddy',
 'Buddy4studdy',
 'Bueno',
 'BuildSupply',
 'BuildTraders',
 'Buildkar',
 'Buildzar',
 'Bumper',
 'Burger Singh',
 'Buttercups',
 'Butterfly Interactive',
 'BuyHatke',
 'CAKART in',
 'CBREX',
 'CBS',
 'CCAvenue',
 'CCavenue',
 'CREO',
 'CRON Systems',
 'CaRPM',
 'Cabsguru',
 'Call Health',
 'Campus Diaries',
 'CanvasFlip',
 'Canvera',
 'Canvs',
 'Capabiliti',
 'Capillary',
 'Capillary Tech',
 'Capita World',
 'Capital Float',
 'Capricoast',
 'Capzest',
 'CarDekho',
 'CarDekho com',
 'CarTrade',
 'CarTrade com',
 'Caratlane com',
 'Caravan Craft',
 'Caravan Craft Retail',
 'Carcrew in',
 'Care24',
 'Career Anna',
 'Career360',
 'CareonGO',
 'Careongo',
 'Carlunknownxe2unknownx80unknownx99s Jr',
 'Cars24',
 'Cartisan',
 'Cartrade',
 'CarveNiche',
 'Casa2inns',
 'Cash Suvidha',
 'CashFree',
 'Cashe',
 'Cashflo',
 'Cashify',
 'Cashkaro',
 'Cashkaro com',
 'Cashkumar',
 'Celerix',
 'Celes Care',
 'Cerebroz',
 'Chaayos',
 'Chai Point',
 'Chai Thela',
 'ChaiPoint',
 'Chakr Innovation',
 'Changer Mints',
 'ChargeBee',
 'Chargebee',
 'Chargein',
 'ChatOnGo',
 'CheersOye!',
 'Chefs Basket',
 'Chevon',
 'Chikoop',
 'Chillr',
 'ChipperSage',
 'Chloroplast Foods',
 'ChqBook',
 'Chrysalis',
 'Chumbak',
 'Chymera VR',
 'CimplyFive',
 'Citrus Payment',
 'CityFlo',
 'CityFurnish',
 'CityShor',
 'Civilsdaily',
 'Clapsnslaps',
 'CleanseCar',
 'ClearTax',
 'Cleartax',
 'Cleartrip',
 'CleverSharks',
 'CleverTap',
 'Click2Clinic',
 'Clip App',
 'Clodura',
 'Clonect Solutions',
 'Cloud Lending',
 'Cloudacar',
 'Cloudcherry Analytics',
 'Cloudrino',
 'Clovia',
 'Clumio',
 'Co Life',
 'Codemojo',
 'CodingLabs',
 'CoinTribe',
 'CollPoll',
 'CollateBox',
 'Collateral Medical',
 'Collectabillia',
 'CollegeDekho',
 'CollegeDunia',
 'Comarete',
 'Commeasure',
 'Commonfloor',
 'Commut',
 'ConfirmTKT',
 'ConfirmtTkt',
 'Connaizen',
 'Connect India',
 'ConnectAbank',
 'Consure Medical',
 'Convegenius',
 'Cooey',
 'Cookaroo',
 'Cookifi',
 'Coolshare',
 'Coppre',
 'Corporate360',
 'Corseco',
 'CouponRaja',
 'CoutLoot',
 'Coutloot',
 'CoveIoT',
 'CoverFox',
 'Coverfox',
 'CraftsVilla',
 'Craftstvilla',
 'Craftsvilla',
 'Crayon Data',
 'CredR',
 'CrediHealth',
 'Credifiable',
 'Credihealth',
 'Credit Mate',
 'Credit Sudhaar',
 'Credit Vidya',
 'CreditMantri',
 'CreditMate',
 'CreditSeva',
 'CreditVidya',
 'Credright',
 'Credy',
 'CroFarm',
 'Crofarm',
 'CropIn',
 'Cropin',
 'Crossahead',
 'Crowdera',
 'Crowdfire (formerly Justunfollow)',
 'Crown-it',
 'CrownIt',
 'Crownit',
 'Cube Consumer Services',
 'Cube26',
 'Cuberoot',
 'Cubito',
 'CueMath',
 'Cuelearn',
 'Cult',
 'Cult Fitness',
 'Culture Machine',
 'CultureAlley',
 'Cupick',
 'CupoNation',
 'Curatio',
 'Cure Fit',
 'CureFit',
 'CureInstant',
 'CureJoy',
 'Curefit',
 'Curie Labs',
 'Curiositi',
 'Curofy',
 'CustomFurnish com',
 'Customer360',
 'CustomerSucessBox',
 'Customfurnish',
 'Cyclops',
 'CyclopsMedtech',
 'Cygnus Hospitals',
 'DAAKI',
 'Daalchini Technologies',
 'Daily Ninja',
 'Daily Rounds',
 'Daily hunt',
 'DailyHunt',
 'DailyNinja',
 'DailyObjects',
 'DailyRounds',
 'DarwinBox',
 'Data Resolve',
 'DataWeave',
 'DawaiLelo',
 'DayBox',
 'Dazo',
 'Deal 4Loans',
 'Deal Street Asia',
 'Deal4Loans / Wishfin',
 'Dealwithus',
 'Dekkho',
 'Delhivery',
 'Delight Foods',
 'Demyto',
 'Derbii',
 'Design Cafe',
 'DesignBids',
 'Devourin',
 'Deyor Camps',
 'Deyor Rooms',
 'Dhruva',
 'Dhruva Space',
 'DiabetOmics',
 'Didi',
 'Digiconectt',
 'Digilend',
 'Digio',
 'Digit',
 'Digital F5',
 'Digital Gorkha',
 'Digital Mall Asia',
 'Dil Mil',
 'Dipper',
 'Direct Create',
 'Diro Labs',
 'DishCo',
 'Disprz',
 'Djubo com',
 'DoSelect',
 'DocPlexus',
 'DocTalk',
 'DocsApp',
 'Doctor Insta',
 'DoctorInsta',
 'DogSpot',
 'DoneThing',
 'Donunknownxe2unknownx80unknownx99t Scratch Your Head',
 'DoodhWala',
 'Doormint',
 'Doxper',
 'Dream Wallets',
 'Dream11',
 'Drip capital',
 'DriveSkool',
 'DriveU',
 'DriversCart',
 'Drivestream',
 'Drivezy',
 'Drivify',
 'DrivoJoy',
 'Droom',
 'Droom in',
 'DropKaffe',
 'Dropkaffe',
 'Drums Food',
 'Druva',
 'Duffl',
 'Dunzo',
 'EPS',
 'EPayLater',
 'ERA',
 'Early Salary',
 'EarlySalary',
 'EarlySalary com',
 'Earth Food',
 'Easy Diner',
 'EasyEcom',
 'EasyFix',
 'EasyGov',
 'EasyKhaana',
 'EasyPolicy',
 'EasyRewardz',
 'EasyRoads',
 'Easypolicy',
 'Eat Shop Love',
 'Eatfresh',
 'Eatlo',
 'Eatonomist',
 'Eattreatonline',
 'Eazy Coach',
 'EazyDiner',
 'Eckovation',
 'Ecolibriumenergy',
 'Ecom Express',
 'Ecozen',
 'EdTechReview',
 'Edelweiss',
 'EdgeFx',
 'Edu4Share',
 'EduAce Services',
 'EduBridge',
 'EduKart',
 'EduPristine',
 'EduRev',
 'Edureka',
 'Edurev',
 'Edyoo',
 'Elanic',
 'ElastiRun',
 'ElasticRun',
 'ElderAid Wellness',
 'Elemential',
 'Elucidata',
 'Emflux Motors',
 'Emiza',
 'Emojifi',
 'Enabli',
 'Enakshi',
 'Endless Robotics',
 'Engineer ai',
 'EngineerBabu',
 'Englishleap com',
 'Entropik',
 'Entropika',
 'Entropy Innovations',
 'Envoged',
 'Epiq Capital',
 'Eruditus',
 'Ethinos',
 'Ethosh',
 'EureQa',
 'EvenGini',
 'EveningFlavors',
 'Events High',
 'Explara',
 'Explore Life traveling',
 'ExtraCarbon',
 'ExtraaEdge',
 'Eywa Media',
 'EzCred',
 'Ezetap',
 'EzySolare',
 'Ezyhaul',
 'Ezytruk',
 'FPL Technologies',
 'FR8',
 'FTCash',
 'FXMartIndia',
 'FYNE',
 'FYRE',
 'Faasos',
 'Faasounknownxe2unknownx80unknownx99s',
 'Faaya',
 'Fab Hotels',
 'FabAlley',
 'FabHotels',
 'FabX',
 'FableStreet',
 'Fabogo',
 'Fabulyst',
 'Faircent',
 'Faircent com',
 'FalconBrick',
 'FarEye',
 'FarMart',
 'Farm Taaza',
 'FarmLink',
 'Farmizen',
 'Fashalot',
 'Fashionablyin',
 'Fashionove',
 'Fashor',
 'FastFox',
 'Fastudent',
 'FeetApart',
 'FiTraQ',
 'Fieldassist',
 'Finance Buddha',
 'Fincash',
 'Find My Stay',
 'FindUrClass',
 'FindYahan',
 'FindmeaShoe',
 'Findow',
 'Findyahan',
 'Fingerlix',
 'Finomena',
 'Finova Capital',
 'Fintellix',
 'Fintobox',
 'Finzy',
 'First Eat',
 'First Moms Club',
 'FirstCry',
 'FirstCry com',
 'FirstTouch',
 'Fisdom',
 'FitMeIn',
 'Fitcircle',
 'Fitmein',
 'Fitnapp',
 'Fitpass',
 'Fitraq com',
 'Fitso',
 'Fitternity',
 'Five Star Group',
 'FixNix',
 'Fixy',
 'Flashdoor',
 'FlatFurnish',
 'Flatchat',
 'Flatpebble',
 'FleetRover',
 'FleetX',
 'Flexiloans',
 'Flexing It',
 'FlickBay',
 'Flickstree',
 'FlipClass',
 'Flipkart',
 'Flipkart com',
 'Flixy Games',
 'Flocareer',
 'Flochat',
 'Flutura',
 'Flyrobe',
 'Flytxt',
 'Focus Digit',
 'FoodAbhi',
 'FoodTalkIndia',
 'Foodmemories',
 'Foodpanda',
 'ForeverShop',
 'Formcept',
 'Fourseven',
 'Fourth Ambit',
 'Fourth Partner Energy',
 'Foyr com',
 'Fracktal Works',
 'Fractal Analytics',
 'Frankly',
 'Frapperz',
 'FreeCharge',
 'Freedom Smart Labs',
 'Fresh Food Concepts',
 'FreshBoxx',
 'FreshDesk',
 'FreshMenu',
 'FreshVnF',
 'FreshWorld',
 'Freshboxx',
 'Freshdesk',
 'Freshee',
 'Freshmonk',
 'Freshworks',
 'Front Desk AI',
 'FroyoFit',
 'Frsh',
 'Frsh co in',
 'Ftcash',
 'Fulfil IO',
 'FunOnGo',
 'Funcart',
 'Funcastic',
 'Fundamentor',
 'FundsIndia com',
 'Furdo',
 'Furlenco',
 'Furtados School of Music',
 'Fusion Microfinance',
 'Fxkart com',
 'Fyle',
 'Fyle Technologies',
 'Fynd',
 'GIBBS',
 'GIBSS',
 'GOQii',
 'Gaana',
 'Gaana com',
 'Gadgets 360',
 'Gadgetwood',
 'Gajty',
 'Galleri5',
 'GameXS in',
 'GameZop',
 'Gameezop',
 'Gaming Monk',
 'Gamooz',
 'Gapoon',
 'Garage On Road',
 'GenNext Students',
 'Genextstudents',
 'Genie',
 'Genius Corner',
 'Get My Parking',
 'Get Simpl',
 'GetFocus',
 'GetMyPeon',
 'GetVee',
 'Giftxoxo',
 'GigIndia',
 'Gingercrush',
 'Girnar Software',
 'Glam Studios',
 'GlamStudios',
 'Glamrs',
 'Glassic',
 'GlowRoad',
 'Glowroad',
 'Glowship',
 'GoBumpr',
 'GoChoppers',
 'GoComet',
 'GoDesi',
 'GoFro',
 'GoFynd',
 'GoGo Truck',
 'GoJavas',
 'GoMechanic',
 'GoPigeon',
 'GoQii',
 'GoYaNo',
 'GoZefo',
 'Goalwise',
 'Gobolt',
 'Godof Hospitals',
 'GoldFarm',
 'GolfLAN',
 'Gomalon',
 'Good Methods Global',
 'Goodbox',
 'Goodera',
 'Goodservice',
 'Goomo',
 'Goqii',
 'Gozoomo',
 'Grab',
 'Grab in',
 'GrabOnRent',
 'Grabhouse',
 'Grabhouse com',
 'Gradopedia',
 'GramCover',
 'Gramophone',
 'GrandOpinion',
 'Graphene',
 'Graphic India',
 'Gray Routes',
 'Greenlight Planet',
 'Grex',
 'Grey Campus',
 'Grey Orange',
 'GreyAtom',
 'GreytHR',
 'Gridle',
 'Grofers',
 'Groupon India',
 'Grover Zampa',
 'Grow Fit',
 'GrowFitter',
 'Groww',
 'Guarented',
 'Guiddoo',
 'Guidoo',
 'GuruG Learning',
 'Gurukul',
 'Gyaanzone',
 'GyanDhan',
 'GymTrekker',
 'Gympik',
 'Gympik com',
 'HEAL Institute',
 'HUG Innovations',
 'HWell24',
 'HWell24 Plus',
 'HackerEarth',
 'HackerRank',
 'HalaPlay',
 'HandyHome',
 'HandyTrain',
 'Hansa Customer Equity',
 'Hansel io',
 'Happily Unmarried',
 'HappilyUnmarried',
 'Happitoo',
 'Happy EMI',
 'Happy2Refer',
 'HappyGoEasy',
 'Happydemic',
 'Haptik',
 'Haqdarshak',
 'Harness Handitouch',
 'HashLearn',
 'HashTaag',
 'Hasura',
 'HeadOut',
 'Heads Up For Tails',
 'Healers At Home',
 'HealthAssure',
 'HealthCare',
 'HealthEminds',
 'HealthEnablr',
 'HealthFin',
 'HealthIntel',
 'HealthKart',
 'HealthKumbh',
 'HealthMir',
 'HealthSutra',
 'Healthbuds',
 'Healthcare at Home',
 'Healthi',
 'Healthians',
 'Healthians com',
 'HealthifyMe',
 'Healthifyme',
 'Healthsignz',
 'HealthyWorld in',
 'Heckyl',
 'Hello Curry',
 'Hello Tax',
 'HelpChat',
 'HelpShift',
 'Helpi',
 'Heterogenous',
 'Hevo Data',
 'HeyBiz',
 'HeyPillow',
 'HiJinny',
 'High Radius',
 'HighRadius',
 'Highway Delite',
 'Hike',
 'Hike Messenger',
 'HipBar',
 'HipCouch',
 'Hipcask',
 'Hippily',
 'Hipship',
 'HitGrit',
 'Hitwicket',
 'HolaChef',
 'Holachef',
 'HolidayIQ',
 'Holidify',
 'Holisol Logistics',
 'HomeCapital',
 'HomeLane',
 'HomeStudio',
 'Homelane',
 'Homergize',
 'Homers in',
 'Hoopy',
 'Hopping Chef',
 'Hoppingo',
 'Hopscotch',
 'Horntell',
 'Hostel Dunia',
 'Hotelogix',
 'Hotify',
 'House of Msasaba',
 'Housejoy',
 'Housing',
 'Housing com',
 'HousingMan',
 'Houssup',
 'Howdy Ventures',
 'Hubilo',
 'Hugefly',
 'Hungama',
 'HungerBox',
 'Hungry Foal',
 'HyperTrack',
 'HyperVerge',
 'Hypernova Interactive',
 'I Can Stay',
 'IBSFintech',
 'ICHR',
 'ICustomMadeIt',
 'IDG Ventures',
 'IDfy',
 'IFMR Holdings',
 'IGP com',
 'IIM Jobs',
 'IMAX Program',
 'IMbesharam',
 'INDwealth',
 'ION Energy',
 'IOTrek',
 'IQlect',
 'ISFC',
 'Icertis',
 'Idea Bubbles',
 'IdeaChakki',
 'IdeaForge',
 'Ideal Insurance',
 'Ignis Careers',
 'ImageProVision',
 'Imaginate',
 'Imarticus Learning',
 'Impact Analytics',
 'Impact Guru',
 'ImpactGuru',
 'Impartus',
 'InCred',
 'InCred Finance',
 'Inayo',
 'Inc42',
 'Inclov',
 'Increff',
 'Indee',
 'Indi com',
 'India Gifts Portal',
 'India Lends',
 'IndiaLends',
 'Indiamart',
 'IndianRoots com',
 'Indiez',
 'Indifi',
 'IndigoLearn',
 'Indix',
 'Indofash',
 'Indus OS',
 'IndustryBuying',
 'Industrybuying',
 'Infibeam',
 'Infinite Analytics',
 'Infisecure',
 'Infogain',
 'Infoworks',
 'Infurnia',
 'Ink Monk',
 'Inkmonk',
 'Inmobi',
 ...]

In [9]:
df1[df1['investors'].str.contains('IDG Ventures', na=True)][['date','startup','city','round','amount']]

,date,startup,city,round,amount
101,13/04/2019,Tripoto,New Delhi,Series B,35 91 375
222,30/07/2018,Cure Fit,Bengaluru,Private Equity,12 00 00 000
258,02/05/2018,Bizongo,Mumbai,Private Equity,2 20 00 000
309,26/04/2018,POPxo,Delhi,Private Equity,55 00 000
438,07/12/2017,eShakti,Chennai,Debt Funding,23 00 000
477,04/11/2017,Hevo Data,Bangalore,Private Equity,10 00 000
478,06/11/2017,Smart Karma,Bangalore,Private Equity,10 00 000
489,09/11/2017,Mobiliz AR,Bangalore,Private Equity,8 72 000
504,21/11/2017,Heckyl,Mumbai,Private Equity,27 00 000
527,05/10/2017,Little Black Book,New Delhi,Private Equity,10 00 000
659,21/08/2017,Uniphore,Chennai,Private Equity,68 00 000
672,29/08/2017,CureFit,Bangalore,Private Equity,2 50 00 000
698,17/07/2017,Vayana,Pune,Private Equity,40 00 000
947,07/03/2017,Blowhorn,Bangalore,Private Equity,36 50 000
961,16/03/2017,mPaani,Mumbai,Private Equity,13 50 000
963,16/03/2017,POPxo,New Delhi,Private Equity,31 00 000
1011,13/02/2017,Sigtuple,Bangalore,Private Equity,58 00 000
1060,12/01/2017,Hansel io,Bangalore,Private Equity,13 50 000
1201,05/11/2016,Bizongo,Mumbai,Private Equity,30 00 000
1210,14/11/2016,Active ai,Singapore,Private Equity,30 00 000
1214,15/11/2016,PlaySimple,Bangalore,Private Equity,40 00 000
1233,23/11/2016,Infisecure,Mumbai,Seed Funding,6 00 000
1262,03/10/2016,Uniphore,Chennai,Private Equity,20 00 000
1394,23/09/2016,unknownxc2unknownxa0CloudCherry,Chennai,Private Equity,60 00 000
1497,31/08/2016,Flyrobe,Mumbai,Private Equity,53 00 000
1505,04/07/2016,Curefit,Bangalore,Private Equity,1 50 00 000
1535,13/07/2016,RentMojo,Bangalore,Private Equity,50 00 000
1672,04/05/2016,Lenskart,New Delhi,Private Equity,6 00 00 000
1680,05/05/2016,Unbxd,New Delhi,Private Equity,5 00 000
1688,10/05/2016,HealthifyMe,Bangalore,Private Equity,60 00 000
1932,08/02/2016,Xpressbees,Pune,Private Equity,1 25 00 000
1949,15/02/2016,Aasaanjobs,Mumbai,Private Equity,50 00 000
2198,02/11/2015,CityFlo,Mumbai,Seed Funding,7 50 000
2215,06/11/2015,POPxo com,New Delhi,Private Equity,20 00 000
2263,23/11/2015,RentoMojo,Bangalore,Private Equity,20 00 000
2275,26/11/2015,Pluss,Gurgaon,Private Equity,10 00 000
2328,12/10/2015,Tripoto,New Delhi,Private Equity,1 00 000
2520,13/08/2015,Agrostar,Pune,Private Equity,40 00 000
2570,01/07/2015,Cloudcherry Analytics,Chennai,Seed Funding,10 00 000
2634,23/07/2015,iCrushiFlush,Mumbai,Seed Funding,3 20 000
2651,29/07/2015,Zimmber,Mumbai,Private Equity,20 00 000
2741,26/06/2015,CreditMantri,Chennai,Private Equity,25 00 000
2760,05/05/2015,Fintellix,Bangalore,Private Equity,1 50 00 000
2764,07/05/2015,Uniphore,Chennai,Private Equity,1 50 00 000
2818,08/04/2015,FirstCry com,Pune,Private Equity,1 00 00 000
2875,03/03/2015,Vserv,Noida,Private Equity,1 50 00 000
2897,16/03/2015,NestAway,Noida,Seed Funding,13 00 000
2904,19/03/2015,Tripoto,Noida,Private Equity,20 00 000
2952,09/02/2015,MyNoticePeriod,Noida,Private Equity,30 00 000
2987,27/02/2015,Momoe,Noida,Seed\\nFunding,12 00 000
2989,02/01/2015,LensKart,Noida,Private Equity,21 50 000
3034,24/01/2015,Aasaanjobs,Noida,Seed Funding,15 00 000

In [10]:
df1[df1['investors'].str.contains('IDG Ventures')].groupby('startup')['amount'].sum().sort_values(ascending=False,inplace=True)
df1

,date,startup,vertical,subVertical,city,investors,round,amount
0,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,20 00 00 000
1,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,80 48 394
2,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,1 83 58 860
3,02/01/2020,unknown,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,30 00 000
4,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,18 00 000
...,...,...,...,...,...,...,...,...
3039,29/01/2015,Printvenue,Online Travel Marketplace,Interior Design Marketplace,Noida,Asia Pacific Internet Group,Private Equity,45 00 000
3040,29/01/2015,Graphene,Online Travel Marketplace,Interior Design Marketplace,Noida,KARSEMVEN Fund,Private Equity,8 25 000
3041,30/01/2015,Mad Street Den,Online Travel Marketplace,Interior Design Marketplace,Noida,"Exfinity Fund, GrowX Ventures.",Private Equity,15 00 000
3042,30/01/2015,Simplotel,Online Travel Marketplace,Interior Design Marketplace,Noida,MakeMyTrip,Private Equity,15 00 000
3043,31/01/2015,couponmachine in,Online Travel Marketplace,Interior Design Marketplace,Noida,UK based Group of Angel Investors,Seed Funding,1 40 000

In [11]:
df1['date']

0       09/01/2020
1       13/01/2020
2       09/01/2020
3       02/01/2020
4       02/01/2020
           ...
3039    29/01/2015
3040    29/01/2015
3041    30/01/2015
3042    30/01/2015
3043    31/01/2015
Name: date, Length: 3044, dtype: object

In [ ]:


df1['date'] = df1['date'].replace('05/072018', '05/07/2018')

# Convert to datetime
df1['date'] = pd.to_datetime(df1['date'],dayfirst=True,errors='coerce')

# Year only
print(df1['date'].dt.month)
df1['year']=df1['date'].dt.year
df1['date'].dt.year
df1.head(2)
df1.to_csv("ClineStatup_Data.csv",index=True)
# Wrong date fix

264   NaN
Name: date, dtype: float64

In [121]:
# total amount
df1 = df1.copy()

df1.loc[:, "amount"] = pd.to_numeric(df1["amount"], errors='coerce')

df1 = df1.dropna(subset=["amount"])
round(df1["amount"].sum())
# maximum ammount
round(df1["amount"].max())

4200000

In [61]:
df3 = pd.read_csv("startup_funding (1).csv")
df3 = df3.copy()

df3["Amount in USD"] = df3["Amount in USD"].astype(str).str.replace(',', '')

df3["Amount in USD"] = pd.to_numeric(df3["Amount in USD"], errors='coerce')

df3 = df3.dropna(subset=["Amount in USD"])

In [63]:
print(df3["Amount in USD"].min())
print(df3["Amount in USD"].max())
print(df3["Amount in USD"].sum())

16000.0
3900000000.0
38057737864.22

In [64]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2065 entries, 0 to 3043
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sr No              2065 non-null   int64
 1   Date dd/mm/yyyy    2065 non-null   object
 2   Startup Name       2065 non-null   object
 3   Industry Vertical  1934 non-null   object
 4   SubVertical        1418 non-null   object
 5   City  Location     1930 non-null   object
 6   Investors Name     2045 non-null   object
 7   InvestmentnType    2062 non-null   object
 8   Amount in USD      2065 non-null   float64
 9   Remarks            337 non-null    object
dtypes: float64(1), int64(1), object(8)
memory usage: 177.5+ KB

In [88]:
df3 = df3.drop(columns=['Date dd/mm/yyyy','Startup Name','Industry Vertical','SubVertical','City  Location','Investors Name','InvestmentnType','Remarks'])

df3 = df3.copy()

df3["Amount in USD"] = df3["Amount in USD"].astype(str).str.replace(',', '')

df3["Amount in USD"] = pd.to_numeric(df3["Amount in USD"], errors='coerce')

df3 = df3.dropna(subset=["Amount in USD"])

# ////////////////

print(df3["Amount in USD"].min())

print(df3["Amount in USD"].max())

print(df3["Amount in USD"].sum())

KeyError: "['Date dd/mm/yyyy', 'Startup Name', 'Industry Vertical', 'SubVertical', 'City  Location', 'Investors Name', 'InvestmentnType', 'Remarks'] not found in axis"

In [89]:
df3.rename(columns={'Amount in USD':'amount'}, inplace=True)

df3.to_csv('statup_amount.csv', index=False)

In [93]:
df4=pd.read_csv('statup_amount.csv')
# round(df4['amount'].sum())
df4['amount_cr'] = (df4['amount'] * 83) / 10000000
df4.head()
int(df4['amount_cr'].sum())

315879

In [117]:
df4.rename(columns={'amount':'Amount'}, inplace=True)
df4.head()

   Sr No       Amount    amount_cr
0      1  200000000.0  1660.000000
1      2    8048394.0    66.801670
2      3   18358860.0   152.378538
3      4    3000000.0    24.900000
4      5    1800000.0    14.940000

In [116]:
new_df = df1.merge(df4, left_on='amount', right_on='Amount')
new_df

KeyError: 'Amount'

In [81]:
data=pd.concat([df1,df4],axis=1)
data.head()
data.rename(columns={'amount':'Amount'}, inplace=True)

'20 00 00 00080 48 3941 83 58 86030 00 00018 00 00090 00 00015 00 00 00060 00 0007 00 00 0005 00 00 0002 00 00 0001 20 00 0003 00 00 00059 00 00020 00 0005 00 00 00023 10 00 00015 00 00 0004 86 00015 00 000undisclosed1 20 00 0002 60 00 0001 74 11 26513 00 00013 50 00 0003 00 00022 00 00 0001 58 00 00028 30 00 00020 00 00 0001 00 00 00 0004 50 00 00058 50 00 000unknown45 00 00033 00 00060 00 00050 00 0001 80 00 00010 00 0001 00 00 00045 00 00 00050 00 0002 00 00 00050 00 00016 00 00014 00 00 0003 80 80 00012 50 00 0001 10 00 0005 10 00 0003 70 00 0005 00 00011 00 00 0001 50 00 00065 90 00010 00 000Undisclosed7 00 00 0003 90 00 00 0001 90 00 00025 00 0001 45 00010 00 0003 80 80 0005 00 00015 00 00 0006 00 00 0001 60 00 00057 50 00025 00 00010 00 0003 19 6055 10 00 0001 00 00 00048 89 975.5490 00 0007 50 00 0002 60 00 00025 00 00027 39 034.682 60 00 0001 51 09 500.004 30 2001 55 00 0005 20 00 00035 84 00034 00 000undisclosed8 68 600undisclosed15 00 00 0005 00 00 0005 10 00 00014 00 00 0001 15 00 00056 00 0004 50 00 0001 70 00 0004 30 66535 91 3752 00 00035 00 00063 20 82024 43 4953 07 0002 60 00 00030 00 00014 342 000+50 00 00030 00 000Undisclosed22 60 00 0006 00 00010 00 00 00011 00 00 0002 20 00 00050 00 0007 00 0005 00 00 0008 00 0005 72 0001 43 00020 00 00035 00 0001 38 9952 77 99 0005 00 00 0005 00 00010 00 00010 00 00013 00 00010 00 0005 00 00030 00 00 00060 00 0002 78 0003 10 00 000Undisclosed34 00 0002 95 00 0004 20 00 00017 00 00017 00 0001 10 00 00082 00 00030 00 00040 00 0001 46 80 0001 20 00 0003 50 00 00022 50 00 00063 90 00010 00 00010 00 00015 72 00 00015 72 00 00010 00 00 00040 00 0003 20 00 00055 00 00050 00 0003 00 00 0004 00 0004 00 00070 00 0001 20 00010 00 0003 50 00 0001 00 00 00040 00 0001 22 00 0006 60 00 00030 00 00010 00 00040 00 00080 00 0001 14 81158 50 00010 00 00048 00 00060 00 0001 42 70 0001 34 00 00042 00 00050 00 00030 00 00060 00 00 00060 00 00 00010 00 00040 00 00062 50 0002 77 00 0004 40 00011 00 0004 37 0004 37 00050 00 00050 00 00025 00 0001 80 0005 00 0001 75 0002 90 00 0004 97 00 00015 00 00010 00 00 00015 00 0001 80 00 0001 80 00 0002 80 0004 36 0001 80 0004 50 00 0001 70 00 00012 50 00025 00 00011 00 00011 00 0005 00 0001 10 00 00012 00 00 00010 00 00 00050 00 0001 00 00 0001 25 0001 25 0001 25 0001 25 0002 30 00 0001 15 00 0002 15 00 0002 15 00 0001 48 00 0001 01 00 00030 00 0003 000 004 50 0004 50 00034 50 00048 00 0002 10 00 00017 00 00017 00 00011 00 0001 50 00 00091 00 00020 00 00 00040 00 00010 00 00089 50 0001 90 00 00045 00 00011 00 00020 00 00020 00 0004 50 0002 20 00 00025 00 0002 25 00010 00 0009 49 0002 40 00 00042000003 00 00070 00 0005 00 0007 35 0007 35 00020 00 00020 00 0002 93 0001 20 00 0002 00 00015 00 00080 00 00080 00 0001 40 00 00013 000 0020 00 0003 07 6003 07 60013 00 0005 50 00 0001 50 0001 00 00 00028 00 0001 000 000 1 000 000 46 14046 1401 20 00 00010 00 00046 000 0020 00 0005 00 0005 00 0002 20 00 0002 20 00 0002 20 00 00011 000 002 30 00 0002 30 00 00019 00 0001 10 00 0001 50 0002 20 00 0002 46 00055 00 00055 00 0001 00 00 0001 00 00 00075 00 0009 78 0009 78 00030 00 0001 20 00 0002 50 00010 00 00021 00 0001 00 00 00060 00 00050 00 00011 00 00097 00 00076 00 0003 84 00 00010 00 00010 00 0008 20 00 0008 20 00 0001 72 00 0006 20 00 00013 10 0005 00 00030 00 00010 00 00010 00 00010 00 0001 80 00 0007 68 00012 40 00012 40 00010 00 0002 50 00020 00 0005 35 00030 00 00030 00 00030 00 00 00020 00 00 00043 00 0002 10 00 00020 00 00020 00 00031 00 00010 00 00 00010 00 00 0005 00 00 0001 20 00 0001 20 00 00068 30 00068 30 0008 70 00 0008 70 00 0009 35 0893 11 2003 11 2001 35 00 00030 00 0001 00 0005 00 00050 00 0001 48 43462 30 0002 50 0001 50 00038 00 0005 00 0005 00 00 0002 00 00 00021 00 00021 00 0007 72 50010 40 00010 40 0002 50 00011 50 00 00014 00 00014 00 00014 00 0001 57 00 0001 57 00 0001 57 00 00047 00 00025 00 00019 30 0001 88 40 0002 35 00 0003 62 30 00080 0002 00 00 0003 54 6002 50 00 0002 00 00 00010 00 0001 82 00 0004 00 00025 00 00025 00 00040 00 00032 00 00030 00 0004 70 00 00086 00 00062 40 00062 40 00010 00 00074 00 00015 00 00010 00 00010 00 0005 00 00 0005 00 00076 00 0001 00 00 00044 00 00044 00 0001 23 00 0002 30 00 00010 00 0005 00 0006 00 00 00070 00 0001 00 00 00031 00 0007 50 00023 00 00050 00 00015 00 00050 00050 00012 00 00018 00 00018 00 0001 75 00 0002 33 0002 70 00 0002 70 00 00072 00 00072 00 00070 00 00060 00 0002 50 0001 00 00 0001 00 00 0005 37 00027 00 00027 00 00095 00 00095 00 00015 00 00010 00 0001 95 00 00040 00 0001 50 0001 50 0001 00 00 0001 00 00 00038 00 0005 70 0005 70 0005 70 00010 00 00010 00 0005 00 00010 00 00010 00 00010 00 00010 00 00050 00 00050 00 00076 00 00030 00 00030 00 00036 00 0008 72 0008 72 0008 72 0002 50 00 0002 50 00 0001 50 00 0001 50 00 00082 50 0009 00 0009 00 00030 00 00030 00 00030 00 0002 00 0002 00 0006 92 0003 29 23027 00 0004 00 0002 50 0002 60 00 0002 60 00 00020 00 00 00020 00 00 00020 00 00 0001 00 00 0002 50 00027 00 00 00039 00038 00 0001 30 00 00015 00 00013 50 00020 00 00020 00 00020 00 00011 00 00 00011 00 00 0003 06 0003 87 00 00010 00 0004 50 00092 00 00031 00 00080 00 0001 00 00 00020 00 00020 00 00027 00 00027 00 00027 00 0003 36 0003 36 00014 00 00045 00 00031 00 00011 00 0002 35 0007 70 00 0002 50 00020 00 00080 00 00092 00 00070 00 00070 00 00070 00 00077 00 0005 00 00070 00 00060 00 00031 00 0001 18 0001 18 0005 00 00030 00 0007 22 0007 22 0007 22 0005 50 00050 00 00038 00 00038 00 0001 20 00077 00 00020 00 0001 40 00 0003 20 00 00010 00 00015 00 00013 00 00056 00 00015 00 0006 00 0001 07 50 0001 00 00 00060 00 0002 60 00 00050 00 00050 00 00025 00 00 0007 80 0007 80 00010 00 00069 00 00069 00 0003 00 00 00062 00 00062 00 0001 00 0001 70 00 00030 00 00030 00 00020 00 0001 00 00 0001 15 00 0007 80 0007 80 0004 40 00 0001 20 0001 20 00010 00 00010 00 0005 00 00 0005 00 00 00060 00 00060 00 00060 00 00010 00 0001 54 00 0001 54 00 0001 54 00 00060 00 00060 00 00060 00 0004 22 0001 50 0001 50 0001 50 0001 50 00016 00 00016 00 00010 00 00010 00 0003 00 00010 00 00013 00 00013 00 00013 00 0005 00 0008 50 0003 00 0003 00 0003 00 0003 00 0003 00 0003 00 0003 00 0003 00 0002 43 0002 20 00031 00 0007 83 0007 83 0007 83 0002 50 00 00 0002 50 00 00 0003 60 00 0003 60 00 0003 12 0003 85 0003 85 0001 87 00068 00 0007 34 0007 34 0007 34 0007 34 0008 00 00 00023 00 00023 00 0005 00 0001 60 00 0007 50 0001 25 00070 00 0002 50 00 0007 50 0007 50 0003 40 00 0003 00 00 00010 00 00026 00 0002 00 00 00085 00 0001 20 00 00010 00 00010 00 00010 00 00010 00 00010 00 00030 00 00022 50 0004 64 0004 64 0001 85 00 0001 85 00 0001 85 00 0001 85 00 0005 40 00017 00 00020 00 00040 00 00040 00 00040 00 00040 00 00040 00 0001 00 00 0001 00 00 0006 00 0007 00 0002 00 0002 00 0002 00 0002 00 00012 00 0003 50 00 0003 50 00 0002 50 00 0002 00 0001 50 00 0001 50 00 00012 50 00012 50 00012 50 0002 34 0005 00 00 0005 00 00 00010 00 00010 00 00010 00 00012 00 00010 00 00010 00 00010 00 0006 50 0006 00 0002 32 00015 00 00015 00 0003 50 0003 00 0002 50 0002 50 00078 00 0005 00 00010 00 0007 76 0001 50 00 0001 50 00 00055 00 00055 00 0005 00 00 0005 00 00 0005 00 0001 23 00 00010 00 0001 00 00020 00 00020 00 00020 00 00020 00 0001 25 00 00040 00 0003 00 00052 00 00024 00 00045 00 0002 15 0003 10 00 0003 10 00 00046 00 00020 00 0005 00 00040 00 00010 00 00050 00 0007 10 00 00040 00 00050 00 00050 00 0003 11 0003 11 00030 00 00020 00 00010 00 00010 00 00050 00 0002 10 00 0007 37 00 0001 00 00 00015 00 0001 00 00 0001 00 00 0003 90 00010 45 00 00010 00 00010 00 00010 00 00010 00 00010 00 00010 00 0002 33 0007 00 0007 00 0007 00 00010 00 00050 00 00032 00 00050 00050 00050 00050 00050 00014 00 00077 00 0006 00 0006 00 00040 00 00040 00 00040 00 00050 00 00050 00 0004 66 00010 00 0005 00 0005 00 0005 00 00030 00 0005 00 0002 50 00053 00 00010 00 00010 00 0001 40 00 00 00010 00 00010 00 00010 00 0003 00 00 0005 00 0005 00 00066 00 00066 00 00010 00 0005 80 00080 00 00080 00 00080 00 00080 00 00080 00 00035 00 00035 00 00035 00 00015 00 0008 00 00 00050 00 00070 00 00038 00 00082 00 00082 00 0004 00 00 0004 00 00 0004 00 00 00027 00 00061 00 00036 90 00070 00 0005 00 0005 00 0005 00 00030 00 00030 00 0002 10 00 00050 00 00050 00 00050 00 00050 00 0001 80 00 0001 80 00 00046 00 0001 50 00023 00 00055 00 0001 00 0001 00 00040 00 00045 00 00045 00 00021 00 00021 00 00021 00 00021 00 00077 00 00026 00 00 0003 10 00015 00 00015 00 00015 00 0001 75 0006 20 0006 20 00046 50 00020 00 0006 00 00012 50 0001 55 00030 00 00030 00 00010 00 00063 00 00025 00 00 00032 00 00032 00 0002 45 00031 00 0002 00 00 0002 00 00 0001 10 00 00015 00 00010 00 00010 00 00036 00 00036 00 00036 00 00015 00 0007 50 0007 50 0007 50 00033 00 00 0001 00 00 0001 00 00 0001 00 00 00015 00 0005 00 00025 00 00025 00 00076 00 00076 00 0002 75 0002 75 00067 00 00067 00 00020 00 00 0001 95 00 00012 00 0001 50 00017 90 0001 00 00 0001 00 00 00010 00 00030 00036 50 0001 50 00 00011 00 0001 20 0001 20 0005 00 00045 00 0004 43 0004 43 0006 00 0006 00 0006 00 00033 50 0001 00 00013 50 00013 50 00031 00 0002 00 0002 00 0001 40 00 00 00036 70 00053 00 00053 00 0001 91 0001 50 00 0005 60 00 0003 82 0003 82 00010 00 00 00010 00 00 0005 00 0005 00 0003 00 0003 00 0003 25 0006 50 0006 50 0001 00 00 00050 00050 00050 00050 0001 55 00030 00 00070 00 00070 00 00070 00 0002 50 00 0002 50 00 0002 50 00 00025 00 00025 00 0004 50 0001 00 00 00010 00 00012 00 0005 50 00 0005 50 00 00040 00060 00 00060 00 00080 00 0005 00 0005 00 00058 00 00075 00 00032 00 0001 50 00 0003 30 0004 00 0003 00 0002 24 00 0002 24 00 0002 24 00 00065 00 0003 50 00030 00 00030 00 0005 00 0004 00 0001 52 00 0001 52 00 0001 52 00 00040 00040 0003 87 00 0001 50 00 00040 00011 00 00011 00 00011 00 00011 00 0003 75 00094 00010 00 0007 00 00 0003 66 0008 25 0008 25 0008 25 0008 25 0008 25 0008 25 0001 30 00 0005 70 00 0003 50 00 0008 00 00050 00 00022 50 00022 50 0001 00 00035 00 00035 00 00013 50 0001 00 00 00041 00 00041 00 0004 40 00045 00 00045 00 00045 00 00050 00 00050 00 0007 00 0008 00 00020 00 0005 50 00 0004 41 0005 00 0001 47 0001 47 0001 47 0006 50 0003 00 0003 00 00010 00 00010 00 00010 00 00010 00 00010 00 00010 00 00010 00 00050 00050 00050 0001 50 00 0001 50 00 0001 50 00 0005 00 0001 00 00 00040 00 00040 00 00040 00 00040 00 00040 00 00022 00 00088 00 00088 00 00014 00 0003 00 0003 00 0001 06 00022 50068 00018 00018 00020 00 00020 00 00012 00 00040 00 00036 00 0001 00 0001 00 00030 00 00030 00 00014 00 00014 00 0001 47 0001 47 0001 47 0001 47 0001 47 0001 47 00090 00 0004 40 0004 40 00065 00 0002 50 00060 00 00060 00 0004 50 0002 50 0001 00 00 0002 00 00020 00 00020 00 00020 00 0001 00 00 0001 00 00 0001 11 00 0001 11 00 0001 50 00010 00 00010 00 00010 00 0002 97 0001 00 0001 00 00 0003 50 00 00030 00 0002 30 00 0001 23 0001 23 00074 00 00050 00050 00050 0001 50 00 0001 50 00 0005 00 0005 00 0001 62 0001 62 0003 24 0003 00 00020 00 00020 00 00020 00 00020 00 00020 00 00020 00 00020 00 00012 00 0001 00 00 00050 00 00050 00 00010 00 00010 00 00010 00 00010 00 0002 00 0005 50 00 0001 50 0001 50 0001 50 00060 00 00060 00 0001 00 00 0001 00 00 00010 00 0001 50 0001 50 0001 50 00045 00030 00 0007 50 00 00030 00 00020 00 0001 20 00 00010 00 00010 00 00010 00 00010 00 00030 00 00020 00 00020 00 00060 00 00040 00 00050 00 00050 00 0001 35 00 0001 35 00 0001 35 00 0001 47 00010 00 00010 00 00010 00 00090 0006 50 00050 00 0001 47 0001 47 00050 00 00050 00 0001 47 0002 00 00 0006 00 0001 00 00 0001 00 00 0001 00 00 00040 00 00040 00 00040 00 00040 00 00040 00 00040 00 00040 00 0001 00 00020 00 00020 00 00030 00 00010 00 0009 63 0001 50 0002 00 00020 00 0002 18 0001 00 0004 40 0005 00 0005 00 0005 00 0005 00 00050 00 00050 00 00020 00 0002 00 0004 50 0004 50 0004 50 00020 00 00042 00 00030 00 00030 00 00010 00 00025 00 00037 50 00037 50 00037 50 00037 50 00012 00 00012 00 0003 00 0003 00 00010 50 0001 00 00022 00 0001 50 00 0001 50 00 0003 75 0005 00 00 0005 00 0005 00 00020 00 00020 00 00020 00 0004 50 00025 00070 00 00060 00 00060 00 00060 00 00060 00 0002 50 00 0002 27 00010 00 00010 00 00010 00 0003 00 0001 60 00 0001 50 0001 50 0001 50 00025 00 00025 00 0003 00 00 00011 00 0007 50 0007 50 0007 50 0007 50 0003 00 0003 00 00030 00 00075 00 00060 00 0005 00 0005 00 0005 00 0001 00 00010 00 00010 00 00010 00 0007 00 0009 71 0002 70 00 0002 70 00 0001 00 0001 00 0001 00 0007 50 00010 00 00010 00 00067 00 00067 00 00067 00 00067 00 00067 00 00067 00 00013 50 0005 00 0005 00 0009 00 00080 00 0005 00 00060 00 0003 15 0006 70 0002 00 0005 00 00 0005 00 00 0005 00 00 0001 50 0004 50 0004 50 0004 48 00030 00 0001 23 00 0003 00 0003 00 0003 00 0003 00 00025 00 00025 00 0001 50 0001 50 0002 00 00050 00 00015 00 0001 00 00010 00 0007 50 0007 50 0001 50 00 0001 50 00 0005 00 0005 00 00010 00 00010 00 0003 13 00 0002 98 0003 50 00060 00 00060 00 0004 25 00010 00 0007 45 00060 00 00060 00 00060 00 00060 00 00060 00 00060 00 00015 80 00015 80 0005 00 00010 00 00010 00 0005 10 00 0001 80 0001 80 00015 00 00015 00 0001 90 00 0001 90 00 0001 20 00 0002 00 0002 75 00030 00 00025 00 00018 00 00018 00 00010 00 00010 00 0002 25 0008 90 0005 00 0005 00 0005 00 00027 00027 00040 0004 45 0002 00 0002 00 0002 00 0005 00 0006 00 00070 00 00070 00 0002 09 0001 50 00 00015 00 00015 00 0001 56 00 0005 00 0005 00 0005 00 0005 00 0006 20 00 00017 50 00 0005 00 00015 00 0002 50 0002 50 0003 75 0003 75 0006 75 0006 75 0006 75 0006 75 0002 00 00 0003 75 0003 75 0003 75 0003 70 00 0003 70 00 0003 70 00 0001 00 0001 00 0002 00 0002 00 00010 00 0001 00 0005 00 0005 00 0005 00 0009 00 00030 00 00030 00 00030 00 00030 00 00030 00 00030 00 0002 40 00 0005 00 0004 00 00 0005 50 0005 50 00030 00 00070 00 00070 00 00010 00 0001 50 00 0001 49 0001 04 0006 00 00 00020 00 00030 00 00030 00 00053 00 00053 00 00053 00 00053 00 0005 00 0005 00 0007 00 0007 00 0001 50 00 0002 00 00020 00 00020 00 0001 60 00 00010 00 0008 20 00 00017 00 0007 40 0002 50 0002 97 00020 00 00010 00 00010 00 00010 00 00010 00 00019 50 00060 00 00035 00 00030 00 0001 22 50 0001 22 50 0001 22 50 0001 22 50 0001 22 50 00050 00 00050 00 0006 00 00013 50 00013 50 00050 00 00050 00 00050 00 0004 50 00010 70 00010 70 00010 00 00020 00 00020 00 0002 50 0002 50 00060 00 0006 50 0006 50 0003 00 00 0003 00 00 0003 00 00 0001 00 00 0001 50 00 00010 00 0002 50 00010 00 0005 95 0005 95 00010 00 00010 00 0005 95 0005 95 0005 95 0005 95 0005 95 0005 95 00010 00 00010 00 00010 00 00010 00 00075 00020 00 0004 48 00040 00 00020 00 0001 00 0002 30 00 00010 00 00010 00 0005 00 0002 00 0002 00 0002 00 0001 60 00 0001 60 00 0002 00 0002 00 0002 00 00020 00 00020 00 0005 00 0005 00 0005 00 0005 00 0005 00 0005 00 0005 00 0005 00 00010 00 00030 00030 00030 00030 00060 00 00010 00 00044 00 0004 50 0004 50 0004 50 0006 00 0006 00 0006 00 0002 00 00 0002 00 00 0001 20 00 0009 00 00052 00 00052 00 00052 00 00052 00 00052 00 00052 00 0001 50 0001 50 0001 50 0001 50 0004 00 0002 25 0002 25 0001 50 00060 00 0001 50 00035 00 0002 10 0002 10 0002 10 00050 00050 0005 00 00060 00 00030 00 0001 48 00012 00 0001 00 0001 00 00030 00 00080 00 0003 00 0003 20 00 0002 95 0002 95 0002 95 0001 00 00050 00050 00015 00 0002 50 00 0002 20 0002 20 0003 68 0003 68 0003 76 0001 45 0001 45 0005 00 00 0005 00 00 0002 50 0002 50 0001 80 0001 80 0002 00 0006 00 00 0001 20 00 0002 00 0002 00 0001 50 0005 00 0005 00 0005 00 0005 00 0003 75 00010 00 00010 00 00075 00027 50 0004 50 0002 50 00060 00 00015 00 0001 80 00 00015 00 00070 00 0009 00 0009 00 00010 00 00 0005 00 0002 50 00 0001 50 0001 50 0001 50 0001 50 0001 50 0001 35 00 00022 00 00010 00 00010 00 00010 00 00010 00 00010 00 0002 50 0001 00 0001 00 0001 00 00 00010 00 00010 00 00010 00 00010 00 0005 00 0005 00 0003 00 0003 00 00089 00089 00010 00 00010 00 00015 00 0001 00 0001 00 00020 00 00020 00 0004 75 0004 75 0002 00 0002 00 00044 00 00089 00 00089 00 00089 00 0001 75 00027 00 00027 00 00027 00 00027 00 00027 00 0002 50 00 0002 50 00 0002 50 00 0002 50 00 0002 50 00 00010 00 0005 00 00060 00 00010 00 00010 00 00010 00 00010 00 00040 0002 00 0002 00 00010 00 00 0003 00 00010 00 00010 00 00010 00 00010 00 00010 00 0001 50 0002 50 0007 50 0007 50 0001 00 0001 00 00010 00 00010 00 0001 50 00 0001 50 00 0001 50 00 0003 00 00 0001 50 0001 50 0001 50 0001 50 0001 50 0001 00 00 0001 00 00 00015 00 0004 50 0004 50 00020 00 00020 00 00020 00 00020 00 0001 50 00 0001 50 00 0001 50 00 0001 50 00 0001 50 00 0001 50 00 0001 50 00 00030 00 00030 00 00030 00 0004 50 0002 00 0002 00 0005 50 0001 50 00 00013 00 0001 50 00 0005 00 0005 00 0005 00 0004 50 0004 50 0006 00 00012 00 0005 00 0001 00 0001 00 0001 00 0001 00 0001 00 0006 00 0006 00 00014 00 00014 00 00010 00 0005 00 0005 00 00010 00 00010 00 0001 50 0001 50 0001 00 0001 00 00040 00 0005 00 00030 00 0005 00 0002 50 0002 50 0001 00 0001 00 0001 00 0001 00 0007 50 00080 00 0006 50 0006 50 0005 00 00025 00 00010 00 00010 00 0004 00 0004 00 0001 11 00 0001 11 00 0001 50 00 00010 00 00010 00 0002 23 6081 49 00 0001 49 00 00010 00 0001 50 0002 50 0001 80 0001 80 0001 80 0002 50 0002 00 0002 30 0008 00 0001 08 00015 00 00030 00030 00030 00020 00 0007 50 00 00015 00 00 0006 00 0006 00 0006 00 0003 60 0003 60 0001 00 0003 00 0003 00 0003 30 0003 30 0005 00 0001 50 0003 00 0003 00 0003 00 00047 00 0002 00 0005 00 0005 00 0004 00 0004 00 0004 00 0004 00 00040 00 00040 00 00022 50022 50022 50022 50010 00 0001 00 0001 00 00030 00030 00030 0001 35 00 0001 35 00 0001 35 00 0001 35 00 00010 00 00081 00052 00010 00 00010 00 00010 00 0001 00 0001 00 0001 00 0001 00 0001 00 0001 25 00 0001 25 00 0001 25 00 0001 25 00 0001 25 00 0002 00 0002 00 00012 00 0001 50 0001 50 0001 50 0001 50 0001 50 0001 25 00010 00 00010 00 00040 00 00050 00 00020 00 00 00020 00 00 00020 00 00 00050 0003 00 0005 00 0005 00 00010 00 0009 70 0009 70 00040 00 00040 00 00040 00 00040 00 0003 50 0003 50 0001 00 00 00050 00 00050 00 00050 00 00073 00073 00073 0003 00 0003 50 00050 00 00050 00 00050 00 0004 00 0004 00 00010 00 00030 00 0001 00 0001 00 00045 00 00037 00037 0001 10 00 0001 10 00 0001 60 0001 60 0001 00 00 0004 00 0001 50 0001 50 00050 00 00050 00 00058 00 00070 0001 45 00025 00 00025 00 0001 30 00 0001 30 00 0001 30 00 0001 30 00 0001 30 00 0001 30 00 00060 00 00060 00 0001 00 0001 00 0001 50 00050 00 00050 00 00050 00 0007 50 00010 00 0001 50 00030 00 0007 50 0007 50 0007 50 0001 60 0001 00 00018 00 00 00050 00 0002 50 00045 00045 00045 00054 00 00054 00 0001 65 00 00010 00 00010 00 00010 00 00 00010 00 00 00023 00 0002 50 00014 50 00 0001 00 0002 40 0002 40 00040 00 00040 00 00040 00 00040 00 0005 20 0005 20 0005 20 0002 00 0002 00 0002 00 0002 00 0002 00 0002 00 00060 00 0003 50 00 0003 50 00 0003 50 00 0003 50 00 00014 00 00050 00 0004 45 00035 00 00035 00 00018 00 0002 00 00 00040 00 00040 00040 00040 0005 00 00022 00 0001 50 00 00030 00 0002 00 0002 00 00072 00 00072 00 00072 00 0005 15 0003 50 00 0003 00 00 0003 00 00 0001 50 0002 10 00 0002 10 00 0002 10 00 00040 00 00010 00 00010 00 00010 00 0003 70 0003 70 0003 70 0003 70 0001 60 0001 60 0001 85 0001 70 00 00051 50 00011 00 00011 00 00011 00 00011 00 00011 00 00010 00 00010 00 00010 00 00056 00 0005 00 0005 00 00020 00 00015 00 00015 00 00015 00 0001 00 0002 00 00 0002 00 00 0002 00 00 0001 00 0001 00 0002 00 00 0002 00 00 0002 00 00 00045 00 0003 00 00 0003 00 00 0002 50 0001 00 0001 00 0001 00 00020 00 00030 00 00030 00 0003 50 00030 00 00030 00 0002 50 00 00050 00 0005 00 0005 00 0001 00 00 0001 00 00 00025 00 0007 00 00 0006 00 0006 00 0006 00 0006 00 0001 50 0001 50 00010 00 00010 00 00035 00 00035 00 0002 00 00030 00 00030 00 00030 00 00010 00 0002 25 00 00020 00 00012 00 00012 00 0003 00 00 00017 00 00017 00 00012 00 00012 00 00012 00 0002 00 00020 00 00040 00 00020 00 00020 00 00020 00 00020 00 00030 00 00030 00 0007 50 0005 00 00010 00 00010 00 00010 00 00050 00 00050 00 0003 03 0003 03 00022 00 00010 00 0005 00 0001 50 00066 00 00066 00 0002 00 0007 50 0007 50 0007 50 00050 00 0001 50 0003 85 0003 20 0005 00 0001 66 00 0002 50 0002 50 0004 00 0001 50 0002 00 0002 00 0002 00 00018 00 00020 00 

In [28]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3044 non-null   object
 1   startup      3044 non-null   object
 2   vertical     3044 non-null   object
 3   subVertical  3044 non-null   object
 4   city         3044 non-null   object
 5   investors    3044 non-null   object
 6   round        3044 non-null   object
 7   amount       3044 non-null   object
 8   year         3037 non-null   float64
dtypes: float64(1), object(8)
memory usage: 214.2+ KB